import React, { useState, useEffect } from 'react';
import {
      Users,
      Home,
      Plus,
      ArrowRight,
      Receipt,
      CheckCircle,
      Clock,
      LogIn,
      Copy,
      TrendingUp
} from 'lucide-react';
import roomService from '../services/roomService';
import { useAuth } from '../context/AuthContext';

const Rooms = () => {
      const { user } = useAuth();
      const [room, setRoom] = useState(null);
      const [loading, setLoading] = useState(true);
      const [joinCode, setJoinCode] = useState('');
      const [createName, setCreateName] = useState('');
      const [expenseForm, setExpenseForm] = useState({ description: '', amount: '' });
      const [isAddExpenseOpen, setIsAddExpenseOpen] = useState(false);
      const [prediction, setPrediction] = useState(null);

      const fetchRoom = async () => {
            try {
                  const data = await roomService.getMyRoom();
                  setRoom(data);
                  if (data) {
                        const pred = await roomService.predictRoomExpense().catch(() => null);
                        if (pred) setPrediction(pred.predicted_expense);
                  }
            } catch (error) {
                  console.error("Error fetching room:", error);
            } finally {
                  setLoading(false);
            }
      };

      useEffect(() => {
            fetchRoom();
      }, []);

      const handleCreateRoom = async (e) => {
            e.preventDefault();
            try {
                  const newRoom = await roomService.createRoom({ name: createName });
                  setRoom(newRoom);
            } catch (error) {
                  alert('Failed to create room');
            }
      };

      const handleJoinRoom = async (e) => {
            e.preventDefault();
            try {
                  const joinedRoom = await roomService.joinRoom({ code: joinCode });
                  setRoom(joinedRoom);
            } catch (error) {
                  alert(error.response?.data?.message || 'Failed to join room');
            }
      };

      const handleAddExpense = async (e) => {
            e.preventDefault();
            try {
                  const updatedRoom = await roomService.addSharedExpense(expenseForm);
                  setRoom(updatedRoom);
                  setIsAddExpenseOpen(false);
                  setExpenseForm({ description: '', amount: '' });
            } catch (error) {
                  alert('Failed to add expense');
            }
      };

      const copyCode = () => {
            navigator.clipboard.writeText(room.code);
            alert('Room code copied!');
      };

      const handleWhatsAppExport = () => {
            if (!room.intelligence?.settlementSummary) return;
            const text = `*Settlement Summary for ${room.name}* 🏠\n\n` +
                  room.intelligence.settlementSummary.join('\n') +
                  `\n\n_Generated by ExpenseML AI_ 🚀`;
            window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
      };

      if (loading) return <div className="text-white">Loading...</div>;

      if (!room) {
            return (
                  <div className="max-w-4xl mx-auto space-y-8">
                        <div className="text-center">
                              <h1 className="text-3xl font-bold text-white mb-2">Welcome to Shared Rooms 🏠</h1>
                              <p className="text-slate-400">Manage shared living expenses with your roommates effortlessly.</p>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                              {/* Create Room */}
                              <div className="glass-card p-8 rounded-2xl border border-blue-500/20 hover:border-blue-500/50 transition-colors">
                                    <div className="w-16 h-16 bg-blue-600/20 rounded-2xl flex items-center justify-center text-blue-500 mb-6 mx-auto">
                                          <Home size={32} />
                                    </div>
                                    <h2 className="text-xl font-bold text-white text-center mb-6">Create a New Room</h2>
                                    <form onSubmit={handleCreateRoom} className="space-y-4">
                                          <input
                                                type="text"
                                                placeholder="Room Name (e.g. 'Boys Hostel')"
                                                value={createName}
                                                onChange={(e) => setCreateName(e.target.value)}
                                                className="w-full bg-[#0B1120] border border-slate-700 rounded-xl p-3 text-white focus:border-blue-500 outline-none"
                                                required
                                          />
                                          <button type="submit" className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-xl transition-colors shadow-lg shadow-blue-600/20">
                                                Create Room
                                          </button>
                                    </form>
                              </div>

                              {/* Join Room */}
                              <div className="glass-card p-8 rounded-2xl border border-purple-500/20 hover:border-purple-500/50 transition-colors">
                                    <div className="w-16 h-16 bg-purple-600/20 rounded-2xl flex items-center justify-center text-purple-500 mb-6 mx-auto">
                                          <LogIn size={32} />
                                    </div>
                                    <h2 className="text-xl font-bold text-white text-center mb-6">Join Existing Room</h2>
                                    <form onSubmit={handleJoinRoom} className="space-y-4">
                                          <input
                                                type="text"
                                                placeholder="Enter Invite Code"
                                                value={joinCode}
                                                onChange={(e) => setJoinCode(e.target.value)}
                                                className="w-full bg-[#0B1120] border border-slate-700 rounded-xl p-3 text-white focus:border-purple-500 outline-none uppercase tracking-widest text-center"
                                                required
                                                maxLength={6}
                                          />
                                          <button type="submit" className="w-full bg-purple-600 hover:bg-purple-700 text-white font-bold py-3 rounded-xl transition-colors shadow-lg shadow-purple-600/20">
                                                Join Room
                                          </button>
                                    </form>
                              </div>
                        </div>
                  </div>
            );
      }

      // Calculate Stats
      const totalExpense = room.expenses.reduce((acc, curr) => acc + curr.amount, 0);
      const memberCount = room.members.length;

      // Sort expenses by date (newest first)
      const sortedExpenses = [...room.expenses].sort((a, b) => new Date(b.date) - new Date(a.date));

      return (
            <div className="space-y-8">
                  {/* Header */}
                  <div className="flex justify-between items-center">
                        <div>
                              <h1 className="text-2xl font-bold text-white">My Room</h1>
                              <p className="text-slate-400 text-sm mt-1">Managed Shared Expenses for <span className="text-white font-semibold">{room.name}</span></p>
                        </div>
                        <div className="flex gap-3">
                              <button
                                    onClick={copyCode}
                                    className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-all border border-slate-700 font-medium text-sm"
                                    title="Copy Invite Code"
                              >
                                    <Copy size={16} />
                                    Code: {room.code}
                              </button>
                              <button
                                    onClick={() => setIsAddExpenseOpen(!isAddExpenseOpen)}
                                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl transition-all shadow-lg shadow-blue-600/20 font-medium"
                              >
                                    <Plus size={18} />
                                    <span>Add Bill</span>
                              </button>
                        </div>
                  </div>

                  {/* Shared Living Intelligence & Quick Stats */}
                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        <div className="lg:col-span-2 glass-card rounded-2xl overflow-hidden border border-blue-500/20 p-6 bg-gradient-to-r from-blue-600/10 to-transparent">
                              <div className="flex justify-between items-center mb-6">
                                    <div className="flex items-center gap-4">
                                          <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center text-white shadow-lg shadow-blue-600/20">
                                                <Home size={24} />
                                          </div>
                                          <div>
                                                <h2 className="text-xl font-bold text-white">{room.name}</h2>
                                                <p className="text-sm text-slate-400 flex items-center gap-2">
                                                      <Users size={14} /> {room.members.length} Members
                                                </p>
                                          </div>
                                    </div>
                                    <div className="text-right">
                                          <p className="text-sm text-slate-400">Total Expenses</p>
                                          <p className="text-2xl font-bold text-white">₹{totalExpense.toLocaleString()}</p>
                                    </div>
                              </div>

                              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                                    <div className="p-4 bg-slate-800/40 rounded-xl border border-slate-700/50">
                                          <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider mb-2">Fairness Scores</p>
                                          <div className="space-y-3">
                                                {room.intelligence?.memberStats?.map((m, i) => (
                                                      <div key={i} className="flex flex-col gap-1">
                                                            <div className="flex justify-between text-xs">
                                                                  <span className="text-slate-300">{m.name}</span>
                                                                  <span className="text-white font-bold">{m.fairnessScore}%</span>
                                                            </div>
                                                            <div className="w-full h-1.5 bg-slate-900 rounded-full overflow-hidden">
                                                                  <div
                                                                        className={`h-full transition-all duration-1000 ${m.fairnessScore > 60 ? 'bg-emerald-500' : m.fairnessScore > 40 ? 'bg-blue-500' : 'bg-amber-500'}`}
                                                                        style={{ width: `${m.fairnessScore}%` }}
                                                                  ></div>
                                                            </div>
                                                      </div>
                                                ))}
                                          </div>
                                    </div>
                                    <div className="p-4 bg-slate-800/40 rounded-xl border border-slate-700/50">
                                          <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider mb-2">Room Dynamics</p>
                                          <div className="flex items-center gap-3 mb-3">
                                                <div className="w-8 h-8 rounded-lg bg-purple-500/10 flex items-center justify-center text-purple-400 text-sm">
                                                      👑
                                                </div>
                                                <div>
                                                      <p className="text-[10px] text-slate-500 uppercase">Top Spender</p>
                                                      <p className="text-sm font-bold text-white">{room.intelligence?.topSpender}</p>
                                                </div>
                                          </div>
                                          {prediction > 0 && (
                                                <div className="mt-4 p-2 bg-purple-500/10 rounded-lg border border-purple-500/10">
                                                      <p className="text-[10px] text-purple-400 font-bold uppercase tracking-widest flex items-center gap-1">
                                                            <TrendingUp size={10} /> Prediction
                                                      </p>
                                                      <p className="text-sm text-white font-bold">₹{prediction.toLocaleString()} Expected</p>
                                                </div>
                                          )}
                                    </div>
                              </div>
                        </div>

                        <div className="glass-card p-6 rounded-2xl border border-emerald-500/20 flex flex-col justify-between">
                              <div>
                                    <h3 className="text-lg font-bold text-white mb-4">One-Tap Settlement</h3>
                                    <div className="space-y-3">
                                          {room.intelligence?.settlementSummary?.map((s, i) => (
                                                <div key={i} className="text-sm text-slate-300 flex items-center gap-2">
                                                      <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full"></div>
                                                      {s}
                                                </div>
                                          ))}
                                          {!room.intelligence?.settlementSummary?.length && (
                                                <p className="text-sm text-emerald-500 font-medium">All settled up! 🧊</p>
                                          )}
                                    </div>
                              </div>
                              <button
                                    onClick={handleWhatsAppExport}
                                    className="mt-6 w-full py-3 bg-[#25D366] hover:bg-[#128C7E] text-white font-bold rounded-xl flex items-center justify-center gap-2 transition-transform hover:scale-[1.02]"
                              >
                                    <span>Export to WhatsApp</span>
                                    <ArrowRight size={18} />
                              </button>
                        </div>
                  </div>

                  {/* Add Expense Form (Inline) */}
                  {isAddExpenseOpen && (
                        <div className="glass-card p-6 rounded-2xl border border-slate-700 animate-in fade-in slide-in-from-top-4 duration-200">
                              <h3 className="text-lg font-bold text-white mb-4">Add Shared Expense</h3>
                              <form onSubmit={handleAddExpense} className="flex flex-col md:flex-row gap-4 items-end">
                                    <div className="w-full md:flex-1">
                                          <label className="block text-sm text-slate-400 mb-1">Description</label>
                                          <input
                                                type="text"
                                                placeholder="e.g. WiFi Bill"
                                                value={expenseForm.description}
                                                onChange={(e) => setExpenseForm({ ...expenseForm, description: e.target.value })}
                                                className="w-full bg-[#0B1120] border border-slate-700 rounded-xl p-3 text-white focus:border-blue-500 outline-none"
                                                required
                                          />
                                    </div>
                                    <div className="w-full md:w-48">
                                          <label className="block text-sm text-slate-400 mb-1">Amount</label>
                                          <input
                                                type="number"
                                                placeholder="0.00"
                                                value={expenseForm.amount}
                                                onChange={(e) => setExpenseForm({ ...expenseForm, amount: e.target.value })}
                                                className="w-full bg-[#0B1120] border border-slate-700 rounded-xl p-3 text-white focus:border-blue-500 outline-none"
                                                required
                                          />
                                    </div>
                                    <button type="submit" className="w-full md:w-auto px-6 py-3 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl transition-colors">
                                          Add
                                    </button>
                              </form>
                        </div>
                  )}

                  {/* Recent Shared Expenses */}
                  <div className="glass-card p-6 rounded-2xl min-h-[300px]">
                        <h3 className="text-lg font-bold text-white mb-6">Recent Shared Expenses</h3>
                        <div className="space-y-4">
                              {sortedExpenses.length === 0 ? (
                                    <p className="text-center text-slate-500 py-10">No shared expenses yet.</p>
                              ) : (
                                    sortedExpenses.map((expense) => (
                                          <div key={expense._id} className="flex items-center justify-between p-4 bg-[#0B1120]/50 rounded-xl border border-slate-700/50 hover:bg-slate-800/50 transition-colors">
                                                <div className="flex items-center gap-4">
                                                      <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-slate-400">
                                                            <Receipt size={18} />
                                                      </div>
                                                      <div>
                                                            <p className="text-sm font-semibold text-white">{expense.description}</p>
                                                            <p className="text-xs text-slate-500">Paid by <span className="text-blue-400 font-medium">{expense.paidBy.name === user.name ? 'You' : expense.paidBy.name}</span> • {new Date(expense.date).toLocaleDateString()}</p>
                                                      </div>
                                                </div>
                                                <div className="text-right">
                                                      <p className="text-sm font-bold text-white">₹{expense.amount.toLocaleString()}</p>
                                                      <p className="text-xs text-slate-500">Split equally</p>
                                                </div>
                                          </div>
                                    ))
                              )}
                        </div>
                  </div>
            </div>
      );
};

export default Rooms;
